### PR TITLE
Theme unit fixes

### PR DESCRIPTION
**Pull request by emeaguiar**

### CODE REVIEW

**Comment by ravichdev** [comment]
Some issues found during QA:

1. Right aligned image overlapping the caption of a right aligned image. (Page: Page Image Alignment)
Screenshot 2020-10-19 at 3 49 28 PM

2. No table borders, I think we should add basic table border styles. (Page: Page Markup And Formatting)
Screenshot 2020-10-19 at 3 52 12 PM

3. Similar as 1, left aligned image overlap/overflow with a full width block below (Post: Block: Cover)
Screenshot 2020-10-19 at 3 59 26 PM

4. Similar to 1 and 3 (Post: Block: Gallery)
Screenshot 2020-10-19 at 4 00 44 PM

5. No spacing padding for columns and container. (Post: Block: Columns)
Screenshot 2020-10-19 at 4 02 25 PM

6. Line height issue for paragraph tag, this is because we set the line-height to px using a CSS mixin, we should change this to use a relative unit like 1.5 for paragraph. (Post: Block category: Common)
Screenshot 2020-10-19 at 4 10 09 PM

7. Full width video is not full width (Post: Block: Embeds)
Screenshot 2020-10-19 at 4 13 23 PM

**Comment by ravichdev** [comment]
@emeaguiar I pushed up fixes for 2, 5, 6 and 7. 1, 3 and 4 seems to because of positioning and the content width of 840px, twenty twenty theme's content width is much less and it due to that content between the floated elements pushes down and created enough space between the floated elements, as the content width is bigger in the Material theme there isn't enough space and we see the overlap issue. Could you take a look and see if you can find a solution ?

**Comment by emeaguiar** [comment]
@ravichdev I have made updates to alignment, I decided to remove absolute positioning and just float them with a bit of margin, example: 

image

I only have one last "issue" (in quotes because it actually works as expected) See the image below, the last image stays a bit further to the left from where it should, this happens because the paragraph is wrapping to the image avobe, and there's not enough space for it to reach the right side.

A solution for this would be to increase the spacing below paraghaphs, but I feel this would be a more noticeable change and I'm not sure if it goes with Material guidelines, so let me know if I should update it.

image

**Review by ravichdev — APPROVED** [review]
Looks good

**Comment by ravichdev** [comment]
@emeaguiar Could you review and test the changes to full-width video, typography mixins etc. ?

**Pull request merged**
